apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: clj-microservices
  labels:
    app: clj-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clj-microservices
  template:
    metadata:
      labels:
        app: clj-microservices
    spec:
      containers:
      - name: frontend
        image: belyklarry/clj-frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: QUOTE_SERVICE_URL
          value: quote-service.clj-microservices.svc.cluster.local:8070
        - name: NEWSFEED_SERVICE_URL
          value: newsfeed-service.clj-microservices.svc.cluster.local:8090
        - name: NEWSFEED_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: authentication-token
              key: token

---      
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: clj-microservices
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: clj-microservices
