apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: clj-microservices
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: belyklarry/clj-frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: QUOTE_SERVICE_URL
          value: ac113344f0e1346bd9a6f4b5d30d37fa-963561801.af-south-1.elb.amazonaws.com:8070
        - name: NEWSFEED_SERVICE_URL
          value: a01a9613e8cc0430d8f246a652ff5671-1777613795.af-south-1.elb.amazonaws.com:8090
        - name: NEWSFEED_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: authentication-token
              key: token

---      
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: clj-microservices
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: frontend
