apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: clj-microservices
  labels:
    app: frontend
    app: newsfeed
    app: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      app: newsfeed
      app: quotes
  template:
    metadata:
      labels:
        app: frontend
        app: newsfeed
        app: quotes
    spec:
      containers:
      - name: frontend
        image: belyklarry/clj-frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: NEWSFEED_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: authentication-token
              key: token

---      
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: clj-microservices
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: frontend
    app: newsfeed
    app: quotes
