apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-deployment
  namespace: clj-microservices
  labels:
    app: clj-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clj-microservices
  template:
    metadata:
      labels:
        app: clj-microservices
    spec:
      containers:
      - name: quotes
        image: belyklarry/clj-quotes:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  namespace: clj-microservices
spec:
  selector:
    app: clj-microservices
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8080
